# -*- coding: utf-8 -*-
"""Day-1 Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10du3R5YHpd1fvPJVZZv9laZrWfWPj1CU
"""

Day-1 Assignment:

list_of_brand = ["Nike", "Puma", "Adidas", "Gems", "Reebok"]

sorted(list_of_brand)   #Acending order

sorted(list_of_brand, reverse=True)    #Decending order

list_of_brands = ["Cadbury", "Nike", "Gems", "Munch", "Adidas"]

sorted(list_of_brands)   #acending order

sorted(list_of_brands, reverse=True)   #Decending order

intersection_set = set.intersection(set(list_of_brand), set(list_of_brands))    #First convert list to set using set(iterable)
intersection_list = list(intersection_set)                                      #Then convert set to list using list(iterable)

intersection_list

Part-2:

for i in range(20,41,2):
  print (i)

for i in range(20,41,2):
  print (i, end = " ")







